//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Store
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [DisplayName("Year opened")]
        [Range(1900, 2018, ErrorMessage ="The year opened field must be a number between between 1900 and 2018")]
        public Nullable<int> Opened { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [DisplayName("Image Link")]
        public string IMGLink { get; set; }
    }
}
